### ISSUE TITLE
when  running '!bash process_data.sh Obama',  Step6 problem

### ISSUE THREAD

**Issue by George-han** [YudongGuo/AD-NeRF#54]
hello:
excuse me, when i  running '!bash process_data.sh Obama',  Step6 does not appeared  but error occured  ''img = self.renderer(mesh)  
TypeError: 'NoneType' object is not callable '',  then  ''[Errno 2] No such file or directory:  'dataset/Obama/track_params.pt' '' appeared too, could you please tell me where the problem is ,thank you

**Comment by islamikoo** [comment]
I copied the files located at /pretrained_models to /dataset/Obama and it worked fine.

**Comment by supy0001** [comment]
I copied the files in /pretrained_models to /dataset/Obama but it didn't work fine. By the way, when I ran  bash process_data.sh, there was an error came up in step 3 shown below:

File "/home/ubuntu/miniconda3/envs/Nerf/lib/python3.6/site-packages/pytorch3d/renderer/blending.py", line 9, in <module>
    from pytorch3d import _C
ImportError: /home/ubuntu/miniconda3/envs/Nerf/lib/python3.7/site-packages/pytorch3d/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at6Tensor7is_cudaEv


I don't know how this error come up. I guess it's due to my conda environment. Can someone tell me how to correct it?

**Comment by VishLivecoder** [comment]
@supy0001 You can just update ua packages and it works.

**Comment by muxiddin19** [comment]
File "data_util/process_data.py", line 113, in <module>
    tmp_img = cv2.imread(os.path.join(ori_imgs_dir, str(valid_img_ids[0])+'.jpg'))
IndexError: list index out of range

In my case in --- Step 2: detect landmarks --- I have this problem. Can you help to solve this issue, please?

**Comment by shaoshengsong** [comment]
https://flyfish.blog.csdn.net/article/details/121979096 
@supy0001 I'm sure you're dealing with a match between cuda and cudnn,pytorch and pytorch3d.

**Comment by shaoshengsong** [comment]
He has generated dataset data in his cloud disk, including the files you need.
@George-han The problem you have is the same as supy0001's solution.
https://flyfish.blog.csdn.net/article/details/121979096
